services:
  meshchat:
    image: ghcr.io/liamcottle/reticulum-meshchat:latest
    container_name: reticulum-meshchat
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8000:8000"
    volumes:
      - ${APP_DATA_DIR}/config:/config
